name: Breast Cancer Estimator App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Train the model (Optional)
      - name: Train the model
        run: python model.py

      # Run tests
      - name: Run tests
        run: pytest

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t flask-app .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag and Push Docker image
        run: |
          docker tag flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy application using ArvanCloud API
      - name: Deploy to ArvanCloud PaaS
        uses: hatamiarash7/ar-paas-action@v1.3.0
        with:
          region: 2
          auth: ${{ secrets.R1C_API }}
          namespace: Breast cancer app
          app: test
          container: test-container
          image: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          version: 1.3.3